### ISSUE TITLE
IncQuery cannot find EPackage when it originates from a target platform

### ISSUE THREAD

**Issue by nboldi** [IncQueryLabs/org.eclipse.incquery#1]
Problem message:
```Couldn't resolve reference to EPackage 'http://modelexecution.eltesoft.hu/xumlrt/'.```

The problem only appears when the plugin is loaded from the target definition. If the plugin is open in the workspace everything works as expected.

I reproduced the problem in a small example. In the project there is an eiq file and a target platform definition. When the target platform definition is selected as a target platform the eiq file has the mentioned error. 

https://drive.google.com/file/d/0B_zgplX10IP1aHRSM3FPdEpSTEU/view?usp=sharing

The example may raise other errors after this issue is fixed, but the EPackage should be resolved.

**Comment by abelhegedus** [comment]
Please file this on bugzilla: https://bugs.eclipse.org/bugs/describecomponents.cgi?product=Incquery
